networks:
    default:
        name: datapipeline-network
        external: true
services:
    datapipeline:
        image: datapipeline
        container_name: datapipeline
        volumes:
            - ../../../secrets:/secrets
            - ../datapipeline:/app
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS
            GCP_PROJECT: $GCP_PROJECT
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [gpu]
        runtime: nvidia  # Use NVIDIA runtime for GPU access
        depends_on:
            - chromadb
    chromadb:
        image: chromadb/chroma:latest
        container_name: datapipeline-chromadb
        ports:
            - 8000:8000
        volumes:
            - ./docker-volumes/chromadb:/chroma/chroma
        environment:
            - IS_PERSISTENT=TRUE
            - ANONYMIZED_TELEMETRY=FALSE
            - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"] # This is not recommended for production environments.